### ISSUE TITLE
Migrate to newest version of Storybook

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#397]
# Feature request
**Is your feature request related to a problem? Please describe.**
#247 has been open for a long time.

**Describe the solution you'd like**
Bump Storybook and relevant add-ons to latest version and resolve any bugs that show up in `yarn storybook` and `yarn build-storybook`. Change whatever is needed to get it to work again!

**Comment by KrDimitrov** [comment]
On it! Ill try at least..

**Comment by kylemh** [comment]
Damn. This is a huge undertaking, good on ya!

Let me know if you need any help at all. I'm on Slack all weekend.

I am assigning myself to this issue as a placeholder for your work. Thank you, and good luck! 😁 

**Please note:**
If no activity is shared within two weeks, I will remove my assignment. At that point, the issue will be open for anybody to take.

**Comment by KrDimitrov** [comment]
Welp, its seems im kinda stuck. Storybook starts with no errors, as well as `yarn dev`. 

It seems, svg importing is not working in Storybook. Any other components are rendered properly, but those that import svgs show an `String contains an invalid character` error message (not in console, in browser). 

![Screenshot](https://user-images.githubusercontent.com/29924708/57366605-91135e00-7187-11e9-95b7-94c27d932699.jpg)


I know for a fact that its related to svg importing, and i have tried other importing methods but none of them fixed this issue...

[Updated Branch](https://github.com/KrDimitrov/front-end/tree/update/storybook)

**Comment by kylemh** [comment]
Will you do me a favor and try upgrading your version of `react-svg-loader`? 

[More context on my guess](https://github.com/OperationCode/front-end/pull/470).

**Comment by kylemh** [comment]
@KrDimitrov I dove into your fork and have made a few changes that may get you farther:

1) Run `yarn upgrade-interactive --latest` and upgrade everything except `husky`, `lint-staged`, and `next-redux-wrapper`.

2) Change `.storybook/webpack.config.js` to:
```javascript
const path = require('path');
const svgoConfig = require('../common/config/svgo');
const postCSSConfig = require('../postcss.config');

// Export a function. Accept the base config as the only param.
module.exports = async ({ config, mode }) => {
  // mode has a value of 'DEVELOPMENT' or 'PRODUCTION'
  // You can change the configuration based on that.
  // 'PRODUCTION' is used when building the static version of storybook.

  // remove existing css-loader rules
  config.module.rules = config.module.rules.filter(
    f => f.test.toString() !== '/\\.css$/'
  );

  // extend config to our liking
  config.module.rules.push(
    {
      test: /\.css$/,
      loaders: [
        'style-loader',
        {
          loader: 'css-loader',
          options: {
            modules: true,
            importLoaders: 1,
            localIdentName: '[name]_[local]__[hash:base64:5]',
            sourceMap: true,
          },
        },
        {
          loader: 'postcss-loader',
          options: {
            plugins: [
              // Use PostCSS.config.js, but also use `postcss-export-custom-variables` plugin
              ...postCSSConfig({
                file: {
                  dirname: '../',
                },
                options: config,
                env: mode.toLowerCase(),
              }).plugins,
              require('postcss-export-custom-variables')({
                exporter: 'js',
                destination: 'common/styles/themeMap.js',
              }),
            ],
          },
        },
      ],
      include: path.resolve(__dirname, '../'),
    },
    {
      test: /\.svg$/,
      use: [
        {
          loader: 'react-svg-loader',
          options: {
            svgo: svgoConfig,
          },
        },
      ],
    },
  );

  // Return the altered config
  return config;
};
```

3) Change `.storybook/backgrounds.js` to:
```javascript
import { brandColorsObject } from 'common/styles/styleExports';
import { capitalizeFirstLetter } from 'common/utils/string-utils';

const backgroundsPaletteArray = Object.keys(brandColorsObject).map(name => ({
  name: capitalizeFirstLetter(name),
  value: brandColorsObject[name],
  default: name === 'white',
}));

export default backgroundsPaletteArray;
```

4) Remove `@storybook/addon-options` by running `yarn remove @storybook/addon-options` and removing it's import in `.storybook/addons.js`.

5) Change `.storybook/config.js` to:
```javascript
import React from 'react';
import Router from 'next/router';
import MockedRouter from 'test-utils/mocks/nextRouterMock';
import MockNextContext from 'test-utils/mocks/nextContextMock';
import { addDecorator, configure } from '@storybook/react';
import { setDefaults } from '@storybook/addon-info';
import { checkA11y } from '@storybook/addon-a11y';
import { addParameters } from '@storybook/react';
import { create, themes } from '@storybook/theming';

import backgroundsPaletteArray from './backgrounds';

import 'common/styles/globalStyles.css';

// addon-info
setDefaults({
  header: false,
  maxPropsIntoLine: 1,
});

// Adding global decorators for mocks
// This is a bit like hitting our Storybook with a sledgehammer to resolve an issue with a decorator
// which only a few components utilize. Regardless, the `withInfo` addon renders wrappers when used
// on a story-by-story basis, so we'll default to this unless it causes issues.
Router.router = MockedRouter;

const mockWithRouterDecorator = storyFn => <MockNextContext>{storyFn()}</MockNextContext>;

addDecorator(checkA11y);
addDecorator(mockWithRouterDecorator);
addParameters({
  backgrounds: backgroundsPaletteArray,
  options: {
    theme: create({
      ...themes.dark,
      brandTitle: 'Operation Code',
      brandUrl: 'storybook.operationcode.org',
      // brandImage: ''
    }),
  }
});

// Dynamically load all files matching `*.stories.js` pattern within the components folder
const requireComponents = require.context('../components/', true, /stories\.js$/);

function loadStories() {
  requireComponents.keys().forEach(requireComponents);
  // Add any new component folders with stories here, using the patterns defined above
}

configure(loadStories, module);
```

# It's running!

## Remaining Problems

1) SVGs still don't work (different error), but if you read [this section](https://storybook.js.org/docs/configurations/serving-static-files/#1-via-imports) it looks like we need to setup `file-loader` in the webpack config ourselves when we're in full-control mode. That could resolve the SVG issue.

2) A few other issues with various add-ons which you can see at run-time:
<img width="872" alt="Screen Shot 2019-05-08 at 9 56 33 AM" src="https://user-images.githubusercontent.com/9523719/57393268-9b2d6080-7177-11e9-99a2-fcf7d285afe6.png">

3) The backgrounds addon isn't showing up... Maybe this will resolve itself after you fix #1 and #2, but be aware we should see that tab in the addons section.

**Comment by KrDimitrov** [comment]
Still no results on my end. Did 1-5, I'm still getting the same error, `yarn dev` is broken, as well as commit test, but that is to be expected? I ran 1-5 twice, the first time I installed `file-loader`, still the same error.

Maybe my fork is not up to date with origin?
I'll update it and try again.

**Comment by kylemh** [comment]
Let me know how it goes after updating to origin.

I can dive into your branch again - you’re so close! I’m excited.

**Comment by KrDimitrov** [comment]
Nope, no results sadly. I'm probably missing something small. I rebased and branched off of the updated master. `yarn dev` is not running, and storybook gives me the same error. 

It is important to note that when I ran `yarn upgrade-interactive --latest` there were no updates for `lint-staged`

`yarn dev` errors

```
[ error ] ./components/Footer/Footer.css
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties
[ wait ]  compiling ...
[ error ] ./components/Cards/Card/Card.css
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties
[ event ] build page: /_error
[ wait ]  compiling ...
[ error ] ./components/Footer/Footer.css
ValidationError: CSS Loader Invalid Options
```
and then 
```
options should NOT have additional properties
{ Error: Cannot find module '/home/kris/Documents/Coding/front-end/.next/build-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.loadComponents (/home/kris/Documents/Coding/front-end/node_modules/next-server/dist/server/load-components.js:13:9)
    at DevServer.renderToHTMLWithComponents (/home/kris/Documents/Coding/front-end/node_modules/next-server/dist/server/next-server.js:198:48)
    at DevServer.renderErrorToHTML (/home/kris/Documents/Coding/front-end/node_modules/next-server/dist/server/next-server.js:228:21)
    at DevServer.renderErrorToHTML (/home/kris/Documents/Coding/front-end/node_modules/next/dist/server/next-dev-server.js:145:26)
    at processTicksAndRejections (internal/process/task_queues.js:86:5) code: 'MODULE_NOT_FOUND' }
```

Maybe it's related to recent commits on origin?

**Comment by kylemh** [comment]
I'll dive in, and see if I can set you up for success. Perhaps sometime Sunday?

**Comment by KrDimitrov** [comment]
Sure. I'll keep trying. Would start by making `yarn dev` run..

**Comment by kylemh** [comment]
To be clear, I wouldn't worry about  getting `yarn dev` to work. I'm confident the reason is because the `css-loader` version requires a _weird_ version change for `next-css`.

https://github.com/zeit/next-plugins/pull/350#issuecomment-467656451

So we'd need to "upgrade" to 0.2.1-canary.4

**Comment by KrDimitrov** [comment]
# Success!

storybook appears to be working properly, as well as `yarn dev`! 

cypress seems to fail though, with an `Uncaught SyntaxError: Unexpected token ...`, which is from the app, and the tests fail automatically... `This error originated from your application code, not from Cypress.`

**Comment by kylemh** [comment]
Exciting!

`jsconfig.js` really shouldn’t have the ability to break anything, as it’s just a config file for VS Code. I’d prefer that stay in there, but let’s have a PR open up and see if I can offer any help.

**Comment by KrDimitrov** [comment]
Yes, I am aware, but storybook was spitting out errors because of the `//` comment at line 1, PR is on the way

**Comment by sumitparakh** [comment]
Is this issue still open for all?

**Comment by kylemh** [comment]
Yes. I wouldn't recommend taking it on. @KrDimitrov got as far as we can possibly go without changing the source code of dependencies we rely on.

`next-css` simply needs to be changed a lot.

**Comment by chynh** [comment]
I took a shot at this and was able to migrate to storybook 5.1.11. I know someone was already working on this but seemed like it has not been touched for months. Is it okay if I make a PR?

**Comment by kylemh** [comment]
@chynh that would be huge. I was about to dive into this myself but was waiting for v6 to release.

Feel free to open the PR at will.
